package model

import (
	"github.com/go-openapi/strfmt"
	"github.com/google/uuid"
	basic "github.com/terra-discover/bbcrs-migration-lib/model/basic"
)

// FlightCachingTraveller
type FlightCachingTraveller struct {
	basic.Base
	basic.DataOwner
	SessionID                *uuid.UUID                  `json:"session_id,omitempty" gorm:"type:varchar(36);not null"`
	ParentID                 *uuid.UUID                  `json:"parent_id,omitempty" gorm:"type:varchar(36)" format:"uuid" swaggerignore:"true"` // ParentID
	ParentOrderIndex         *int                        `json:"parent_order_index,omitempty" example:"1"`                                       // helper field to connect infant to its parent order_index
	TrxID                    *string                     `json:"trx_id,omitempty"`                                                               // unique 3rd party flight pax id
	OldTrxID                 *string                     `json:"old_trx_id,omitempty" gorm:"type:varchar(50)"`
	IsGuest                  *bool                       `json:"is_guest,omitempty" example:"false" gorm:"not null" validate:"required"`                                                                                                                                         // is guest
	OrderIndex               *int                        `json:"order_index,omitempty" validate:"required" example:"1"`                                                                                                                                                          // order index
	PassengerType            *string                     `json:"passenger_type,omitempty" example:"adult" gorm:"not null" validate:"required"`                                                                                                                                   // attribute to classify of passenge types e.g:child,adult,infant
	PersonID                 *string                     `json:"person_id,omitempty" format:"uuid" gorm:"type:varchar(36);null" validate:"omitempty,gte=0,lte=36" example:"fcee9740-30ee-4d46-af2f-d58cf49f8642"`                                                                // PersonID
	EmployeeID               *string                     `json:"employee_id,omitempty" format:"uuid" gorm:"type:varchar(36);null" example:"fcee9740-30ee-4d46-af2f-d58cf49f8642" swaggerignore:"true"`                                                                           // EmployeeID
	JobTitle                 *JobTitle                   `json:"job_title,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                              // JobTitle
	NamePrefixID             *uuid.UUID                  `json:"name_prefix_id,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                         // Gender ID
	NamePrefix               *string                     `json:"name_prefix,omitempty" example:"MS" validate:"required_if=IsGuest true,omitempty,specialcharacter"`                                                                                                              // NamePrefix
	FirstName                *string                     `json:"first_name,omitempty" gorm:"type:varchar(70);null" example:"Sienna" validate:"required_if=IsGuest true,omitempty,specialcharacter,gte=1,lte=128"`                                                                // FirstName
	MiddleName               *string                     `json:"middle_name,omitempty" gorm:"type:varchar(70);null" example:"Johnson" validate:"omitempty,specialcharacter,lte=0|gte=1,lte=128"`                                                                                 // MiddleName
	LastName                 *string                     `json:"last_name,omitempty" gorm:"type:varchar(70);null" example:"Mccarty" validate:"required_if=IsGuest true,omitempty,specialcharacter,gte=2,lte=128"`                                                                // LastName
	Gender                   *string                     `json:"gender,omitempty" gorm:"type:varchar(10);null" example:"male" validate:"omitempty,gte=0,lte=6"`                                                                                                                  // optional value ("male" or "female")
	GenderID                 *uuid.UUID                  `json:"gender_id,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                              // Gender ID
	IdCardNo                 *string                     `json:"id_card_no,omitempty" gorm:"type:varchar(36);null" example:"387304370979007"`                                                                                                                                    // IdCarNo
	Email                    *string                     `json:"email,omitempty" gorm:"type:varchar(70);null;check:chk_flight_traveller__email_lowercase,coalesce(email=lower(email),true)=true;" example:"sienna.johnson@petroxyz.com" validate:"required,email,gte=0,lte=256"` // Email
	PassportNumber           *string                     `json:"passport_number,omitempty" gorm:"type:varchar(36);null" example:"XY3481234" validate:"required_if=IsDomesticFlight false,omitempty,specialcharacter,gte=3,lte=15"`                                               // PassportNumber
	PassportExpirationDate   *strfmt.Date                `json:"passport_expiration_date,omitempty" gorm:"type:date" format:"date" swaggertype:"string" validate:"required_if=IsDomesticFlight false"`                                                                           // PassportExpiration
	PassportCountry          *uuid.UUID                  `json:"passport_country,omitempty" format:"uuid" gorm:"type:varchar(36);null" validate:"required_if=IsDomesticFlight false"`                                                                                            // PassportCountry
	PassportImage            *uuid.UUID                  `json:"passport_image,omitempty" format:"uuid" gorm:"type:varchar(36);null"`                                                                                                                                            // as multimedia_description_id
	PassportAsset            *MultimediaDescription      `json:"passport_asset,omitempty" gorm:"foreignKey:PassportImage;references:ID" swaggerignore:"true"`                                                                                                                    // Passport Asset
	Nationality              *uuid.UUID                  `json:"nationality,omitempty" format:"uuid" gorm:"type:varchar(36);null"`                                                                                                                                               // Nationality
	MobileLocationTypeID     *uuid.UUID                  `json:"mobile_location_type_id,omitempty" format:"uuid" gorm:"type:varchar(36);null"`                                                                                                                                   // MobileLocationTypeID  // This is Country ID
	MobileCountryAccessCode  *string                     `json:"mobile_country_access_code,omitempty" gorm:"type:varchar(3)" example:"+62"`                                                                                                                                      // MobileCountryAccessCode, country access code of mobile phone. Relate with MobileLocationTypeID field.
	MobileNumber             *string                     `json:"mobile_number,omitempty" gorm:"type:varchar(20);null" example:"+62398670013" validate:"required,gte=0,lte=32"`                                                                                                   // MobileNumber
	DateOfBirth              *strfmt.Date                `json:"date_of_birth,omitempty" gorm:"type:date" format:"date" swaggertype:"string"`                                                                                                                                    // DateOfBirth
	FrequentFlyerProgramID   *uuid.UUID                  `json:"frequent_flyer_program_id,omitempty" format:"uuid" gorm:"type:varchar(36);null"`                                                                                                                                 // FrequentFlyerProgramID
	FrequentFlyerNumber      *string                     `json:"frequent_flyer_number,omitempty" gorm:"type:varchar(20);null" example:"ABC1234" validate:"omitempty,gte=0,lte=20"`                                                                                               // FrequentFlyerNumber
	Parent                   *FlightCachingTraveller     `json:"parent,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                                 // Parent
	Infant                   *FlightCachingTraveller     `json:"infant,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                                 // Parent
	Person                   *Person                     `json:"person,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                                 // Person
	PrefixName               *NamePrefix                 `json:"prefix_name,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                            // NamePrefix
	BusinessEntity           *BusinessEntity             `json:"business_entity,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                        // Business Entity
	Passport                 *Document                   `json:"passport,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                               // Passport
	PassportEntity           *BusinessEntityDocument     `json:"passport_entity,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                        // Passport Entitiy
	Ktp                      *Document                   `json:"ktp,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                                    // KTP
	KtpEntity                *BusinessEntityDocument     `json:"ktp_entity,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                             // KTP Entitiy
	EmailContact             *BusinessEntityEmail        `json:"business_entity_email,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                  // Email Contact
	MobilePhoneContact       *BusinessEntityPhone        `json:"business_entity_phone,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                  // Mobile Phone Contact
	ProposalProfile          *ProposalProfile            `json:"proposal_profile,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                       // Proposal Profile
	ReservationProfile       *ReservationProfile         `json:"reservation_profile,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                    // Reservation Profile
	ProposalAsset            *ProposalAsset              `json:"proposal_asset,omitempty"  gorm:"-" swaggerignore:"true"`                                                                                                                                                        // Proposal Asset
	ReservationAsset         *ReservationAsset           `json:"reservation_asset,omitempty"  gorm:"-" swaggerignore:"true"`                                                                                                                                                     // Reservation Asset
	ProposalAirTraveler      *AirTraveler                `json:"proposal_air_traveler,omitempty" gorm:"foreignKey:PersonID;references:person_id" swaggerignore:"true"`                                                                                                           // Proposal Air Traveler
	ReservationAirTraveler   *AirTraveler                `json:"reservation_air_traveler,omitempty" gorm:"foreignKey:PersonID;references:person_id" swaggerignore:"true"`                                                                                                        // Reservation Air Traveler
	ProposalFlightSegment    *[]AirTravelerFlightSegment `json:"proposal_air_traveler_flight_segment,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                   // Proposal Air Traveler Flight Segment
	ReservationFlightSegment *[]AirTravelerFlightSegment `json:"reservation_air_traveler_flight_segment,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                // Reservation Air Traveler Flight Segment
	IsValidGender            *bool                       `json:"is_valid_gender,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                        // Gender found in gender table
	IsValidNamePrefix        *bool                       `json:"is_valid_name_prefix,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                   // NamePrefix found in name_prefix table
	IsValidNamePrefixGender  *bool                       `json:"is_valid_name_prefix_gender,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                            // NamePrefix found in name_prefix table and gender match of gender_name relation foreignKey gender_id table gender
	IsDomesticFlight         *bool                       `json:"is_domestic_flight,omitempty" gorm:"-" swaggerignore:"true"`                                                                                                                                                     // NamePrefix found in name_prefix table and gender match of gender_name relation foreignKey gender_id table gender
	Age                      *int                        `json:"age,omitempty" gorm:"-" swaggerignore:"true"`
	Employee                 *Employee                   `json:"-" swaggerignore:"true"`
}
