package migration

import (
	model "github.com/terra-discover/bbcrs-migration-lib/model"
)

// ModelMigrations models to migrate
var ModelMigrations []interface{} = []interface{}{
	// Model Section
	&model.AccessType{},                              //index: 0
	&model.AccessTypeTranslation{},                   //index: 1
	&model.AccessibilityFeature{},                    //index: 2
	&model.AccessibilityFeatureTranslation{},         //index: 3
	&model.AccreditationType{},                       //index: 4
	&model.AccreditationTypeTranslation{},            //index: 5
	&model.AdPlacement{},                             //index: 6
	&model.AdPlacementTranslation{},                  //index: 7
	&model.AdditionalDetailType{},                    //index: 8
	&model.AdditionalDetailTypeTranslation{},         //index: 9
	&model.AdditionalInfo{},                          //index: 10
	&model.AdditionalInfoOption{},                    //index: 11
	&model.AdditionalInfoOptionTranslation{},         //index: 12
	&model.AdditionalInfoTranslation{},               //index: 13
	&model.Address{},                                 //index: 14
	&model.AddressTranslation{},                      //index: 15
	&model.AddressType{},                             //index: 16
	&model.AddressTypeTranslation{},                  //index: 17
	&model.AdministrativeCity{},                      //index: 18
	&model.AdministrativeCityTranslation{},           //index: 19
	&model.AgeQualifyingGroup{},                      //index: 20
	&model.AgeQualifyingType{},                       //index: 21
	&model.AgeQualifyingTypeTranslation{},            //index: 22
	&model.Agent{},                                   //index: 23
	&model.AgentAdPlacement{},                        //index: 24
	&model.AgentAnalytic{},                           //index: 25
	&model.AgentApprover{},                           //index: 26
	&model.AgentAsset{},                              //index: 27
	&model.AgentBusinessPartner{},                    //index: 28
	&model.AgentBusinessPartnerType{},                //index: 29
	&model.AgentCampaign{},                           //index: 30
	&model.AgentConsultant{},                         //index: 31
	&model.AgentContent{},                            //index: 32
	&model.AgentCorporate{},                          //index: 33
	&model.AgentCorporateConsultant{},                //index: 34
	&model.AgentCorporateGroup{},                     //index: 35
	&model.AgentCorporateGroupCorporate{},            //index: 36
	&model.AgentCorporateTeam{},                      //index: 37
	&model.AgentCorporateType{},                      //index: 38
	&model.AgentDestinationGroup{},                   //index: 39
	&model.AgentDestinationGroupDestination{},        //index: 40
	&model.AgentDistributionPartner{},                //index: 41
	&model.AgentDivision{},                           //index: 42
	&model.AgentEmailCategory{},                      //index: 43
	&model.AgentEmailCategoryTranslation{},           //index: 44
	&model.AgentEmailRecipient{},                     //index: 45
	&model.AgentEmailSender{},                        //index: 46
	&model.AgentEmailTemplate{},                      //index: 47
	&model.AgentEmployee{},                           //index: 48
	&model.AgentEmployeeAnalytic{},                   //index: 49
	&model.AgentForm{},                               //index: 50
	&model.AgentHotel{},                              //index: 51
	&model.AgentSupplierHotel{},                      //index: 52
	&model.AgentIdentityRule{},                       //index: 53
	&model.AgentIdentityRuleHistory{},                //index: 54
	&model.AgentIntegrationPartner{},                 //index: 55
	&model.AgentJobTitle{},                           //index: 56
	&model.AgentLanguage{},                           //index: 57
	&model.AgentLoyaltyProgram{},                     //index: 58
	&model.AgentMarkupCategory{},                     //index: 59
	&model.AgentMenu{},                               //index: 60
	&model.AgentMessage{},                            //index: 61
	&model.AgentModule{},                             //index: 62
	&model.AgentOffer{},                              //index: 63
	&model.AgentOffice{},                             //index: 64
	&model.AgentPage{},                               //index: 65
	&model.AgentPaymentGateway{},                     //index: 66
	&model.AgentPreference{},                         //index: 67
	&model.AgentProcessingFeeCategory{},              //index: 68
	&model.AgentProduct{},                            //index: 69
	&model.AgentProductCategory{},                    //index: 70
	&model.AgentReferralSource{},                     //index: 71
	&model.AgentServiceFeeCategory{},                 //index: 72
	&model.AgentSetting{},                            //index: 73
	&model.AgentSite{},                               //index: 74
	&model.AgentSocialNetwork{},                      //index: 75
	&model.AgentSpecialDate{},                        //index: 76
	&model.AgentSpecialDateTranslation{},             //index: 77
	&model.AgentSupplierType{},                       //index: 78
	&model.AgentTaxCategory{},                        //index: 79
	&model.AgentTeam{},                               //index: 80
	&model.AgentTeamConsultant{},                     //index: 81
	&model.AgentTerm{},                               //index: 82
	&model.AgentTheme{},                              //index: 83
	&model.AgentTranslation{},                        //index: 84
	&model.AgentTravelPurpose{},                      //index: 85
	&model.AgentUser{},                               //index: 86
	&model.AgentUserCorporate{},                      //index: 87
	&model.AgentUserCorporateGroup{},                 //index: 88
	&model.AgentUserHotel{},                          //index: 89
	&model.AgentUserHotelSupplier{},                  //index: 90
	&model.AgentUserSupplierType{},                   //index: 91
	&model.AgentUserType{},                           //index: 92
	&model.AgentUserTypeCorporate{},                  //index: 93
	&model.AgentUserTypeCorporateGroup{},             //index: 94
	&model.AgentUserTypeHotel{},                      //index: 95
	&model.AgentUserTypeHotelSupplier{},              //index: 96
	&model.AgentUserTypeSupplier{},                   //index: 97
	&model.AgentUserTypeSupplierType{},               //index: 98
	&model.AgentViewership{},                         //index: 99
	&model.AgentVoucher{},                            //index: 100
	&model.AgentVoucherType{},                        //index: 101
	&model.AgentWidgetType{},                         //index: 102
	&model.AirItinerary{},                            //index: 103
	&model.AirItineraryCancelPolicy{},                //index: 104
	&model.AirItineraryCancelPolicyPenalty{},         //index: 105
	&model.AirItineraryGuaranteePaymentPolicy{},      //index: 106
	&model.AirItineraryModifyPolicy{},                //index: 107
	&model.AirItineraryPayment{},                     //index: 108
	&model.AirItineraryReward{},                      //index: 109
	&model.AirItineraryTotalFare{},                   //index: 110
	&model.AirItineraryTotalFareFee{},                //index: 111
	&model.AirOriginDestinationCriteria{},            //index: 112
	&model.AirOriginDestinationOption{},              //index: 113
	&model.AirPassengerTotalFare{},                   //index: 114
	&model.AirPassengerTotalFareBaggageAllowance{},   //index: 115
	&model.AirPassengerTotalFareBasis{},              //index: 116
	&model.AirPassengerTotalFareFlightSegment{},      //index: 117
	&model.AirPassengerTotalFareMessage{},            //index: 118
	&model.AirPassengerTotalFareTax{},                //index: 119
	&model.AirPassengerTotalFareTaxSummary{},         //index: 120
	&model.AirTicket{},                               //index: 121
	&model.AirTicketFlightSegment{},                  //index: 122
	&model.AirTicketTraveler{},                       //index: 123
	&model.AirTravelPreferenceCriteria{},             //index: 124
	&model.AirTraveler{},                             //index: 125
	&model.AirTravelerCriteria{},                     //index: 126
	&model.AirTravelerFlightSegment{},                //index: 127
	&model.Aircraft{},                                //index: 128
	&model.AircraftTranslation{},                     //index: 129
	&model.Airline{},                                 //index: 130
	&model.AirlineAsset{},                            //index: 131
	&model.AirlineCategory{},                         //index: 132
	&model.AirlineCategoryAirline{},                  //index: 133
	&model.AirlineCategoryTranslation{},              //index: 134
	&model.AirlineTranslation{},                      //index: 135
	&model.Airport{},                                 //index: 136
	&model.AirportTranslation{},                      //index: 137
	&model.Attraction{},                              //index: 138
	&model.AttractionAsset{},                         //index: 139
	&model.AttractionCategory{},                      //index: 140
	&model.AttractionCategoryAsset{},                 //index: 141
	&model.AttractionCategoryAttraction{},            //index: 142
	&model.AttractionCategoryTranslation{},           //index: 143
	&model.AttractionOperationSchedule{},             //index: 144
	&model.AttractionTranslation{},                   //index: 145
	&model.Bank{},                                    //index: 146
	&model.BankAccountType{},                         //index: 147
	&model.BankAccountTypeTranslation{},              //index: 148
	&model.BankTranslation{},                         //index: 149
	&model.BasisType{},                               //index: 150
	&model.BasisTypeTranslation{},                    //index: 151
	&model.BedType{},                                 //index: 152
	&model.BedTypeTranslation{},                      //index: 153
	&model.Benefit{},                                 //index: 154
	&model.BenefitAsset{},                            //index: 155
	&model.BenefitTranslation{},                      //index: 156
	&model.BonusProgram{},                            //index: 157
	&model.BonusProgramTranslation{},                 //index: 158
	&model.BuiltInType{},                             //index: 159
	&model.BuiltInTypeTranslation{},                  //index: 160
	&model.BusinessEntity{},                          //index: 161
	&model.BusinessEntityAccreditation{},             //index: 162
	&model.BusinessEntityAddress{},                   //index: 163
	&model.BusinessEntityContact{},                   //index: 164
	&model.BusinessEntityDocument{},                  //index: 165
	&model.BusinessEntityEmail{},                     //index: 166
	&model.BusinessEntityLoyaltyAccount{},            //index: 167
	&model.BusinessEntityPhone{},                     //index: 168
	&model.BusinessEntityURL{},                       //index: 169
	&model.BusinessServiceType{},                     //index: 170
	&model.BusinessServiceTypeTranslation{},          //index: 171
	&model.CabinType{},                               //index: 172
	&model.CabinTypeTranslation{},                    //index: 173
	&model.CacheAirOriginDestinationCriteria{},       //index: 174
	&model.CacheAirTravelPreferenceCriteria{},        //index: 175
	&model.CacheAirTravelerCriteria{},                //index: 176
	&model.CacheCriteria{},                           //index: 177
	&model.CacheGuestCriteria{},                      //index: 178
	&model.CacheRoomStayCriteria{},                   //index: 179
	&model.CallOut{},                                 //index: 180
	&model.CallOutAsset{},                            //index: 181
	&model.CallOutTranslation{},                      //index: 182
	&model.Campaign{},                                //index: 183
	&model.CancelPolicy{},                            //index: 184
	&model.CancelPolicyPenalty{},                     //index: 185
	&model.CancelPolicyPenaltyTranslation{},          //index: 186
	&model.CancelPolicyTranslation{},                 //index: 187
	&model.Capability{},                              //index: 188
	&model.CapabilityCategory{},                      //index: 189
	&model.CapabilityCategoryCapability{},            //index: 190
	&model.CapabilityCategoryTranslation{},           //index: 191
	&model.CapabilityRecipient{},                     //index: 192
	&model.CapabilitySetting{},                       //index: 193
	&model.CapabilityTranslation{},                   //index: 194
	&model.ChargeType{},                              //index: 195
	&model.ChargeTypeTranslation{},                   //index: 196
	&model.City{},                                    //index: 197
	&model.CityTranslation{},                         //index: 198
	&model.CommissionClaim{},                         //index: 199
	&model.CommissionClaimAirline{},                  //index: 200
	&model.CommissionClaimBookingClass{},             //index: 201
	&model.CommissionClaimCabinType{},                //index: 202
	&model.CommissionClaimDepartureDate{},            //index: 203
	&model.CommissionClaimIssueDate{},                //index: 204
	&model.CommissionClaimOriginDestination{},        //index: 205
	&model.CommissionPolicy{},                        //index: 206
	&model.CommissionPolicyTranslation{},             //index: 207
	&model.CommissionType{},                          //index: 208
	&model.CommissionTypeTranslation{},               //index: 209
	&model.Company{},                                 //index: 210
	&model.CompanyTranslation{},                      //index: 211
	&model.ContactType{},                             //index: 212
	&model.ContactTypeTranslation{},                  //index: 213
	&model.ContentDescription{},                      //index: 214
	&model.ContentDescriptionTranslation{},           //index: 215
	&model.ContentFormat{},                           //index: 216
	&model.ContentFormatTranslation{},                //index: 217
	&model.ConvenienceStore{},                        //index: 218
	&model.ConvenienceStoreTranslation{},             //index: 219
	&model.Corporate{},                               //index: 220
	&model.CorporateAdditionalInfo{},                 //index: 221
	&model.CorporateAirlineFare{},                    //index: 222
	&model.CorporateAsset{},                          //index: 223
	&model.CorporateBalanceTransaction{},             //index: 224
	&model.CorporateCostCenter{},                     //index: 225
	&model.CorporateCreditLimit{},                    //index: 226
	&model.CorporateCreditLimitApprover{},            //index: 227
	&model.CorporateDestinationRestriction{},         //index: 228
	&model.CorporateDestinationRestrictionAsset{},    //index: 229
	&model.CorporateDestinationRestrictionCity{},     //index: 230
	&model.CorporateDestinationRestrictionCountry{},  //index: 231
	&model.CorporateDivision{},                       //index: 232
	&model.CorporateEmailCategory{},                  //index: 233
	&model.CorporateEmailRecipient{},                 //index: 234
	&model.CorporateEmployee{},                       //index: 235
	&model.CorporateGroup{},                          //index: 236
	&model.CorporateInvoiceBatch{},                   //index: 237
	&model.CorporateInvoiceGroup{},                   //index: 238
	&model.CorporateInvoiceGroupType{},               //index: 239
	&model.CorporateJobTitle{},                       //index: 240
	&model.CorporateMarkupCategory{},                 //index: 241
	&model.CorporateMenu{},                           //index: 242
	&model.CorporateModule{},                         //index: 243
	&model.CorporateOffice{},                         //index: 244
	&model.CorporatePayload{},                        //index: 245
	&model.CorporatePreferenceHotelBrand{},           //index: 246
	&model.CorporateProcessingFeeCategory{},          //index: 247
	&model.CorporateProductTypeRestriction{},         //index: 248
	&model.CorporateProject{},                        //index: 249
	&model.CorporateRating{},                         //index: 250
	&model.CorporateRatingType{},                     //index: 251
	&model.CorporateRatingTypeLevel{},                //index: 252
	&model.CorporateRatingTypeLevelTranslation{},     //index: 253
	&model.CorporateRatingTypeTranslation{},          //index: 254
	&model.CorporateServiceFeeCategory{},             //index: 255
	&model.CorporateSetting{},                        //index: 256
	&model.CorporateTravelPolicyClass{},              //index: 257
	&model.CorporateTravelPurpose{},                  //index: 258
	&model.CorporateType{},                           //index: 259
	&model.CorporateTypeModule{},                     //index: 260
	&model.CorporateUser{},                           //index: 261
	&model.CorporateUserType{},                       //index: 262
	&model.CorporateViolationReason{},                //index: 263
	&model.CostCenter{},                              //index: 264
	&model.CostCenterTranslation{},                   //index: 265
	&model.Country{},                                 //index: 266
	&model.CountryContent{},                          //index: 267
	&model.CountryTranslation{},                      //index: 268
	&model.CreditCardType{},                          //index: 269
	&model.CreditCardTypeAsset{},                     //index: 270
	&model.CreditCardTypeTranslation{},               //index: 271
	&model.Currency{},                                //index: 272
	&model.CurrencyConversion{},                      //index: 273
	&model.CurrencyTranslation{},                     //index: 274
	&model.DerivedRateType{},                         //index: 275
	&model.DerivedRateTypeTranslation{},              //index: 276
	&model.Destination{},                             //index: 277
	&model.DestinationAsset{},                        //index: 278
	&model.DestinationGroup{},                        //index: 279
	&model.DestinationGroupCountry{},                 //index: 280
	&model.DestinationGroupTranslation{},             //index: 281
	&model.DestinationSystemType{},                   //index: 282
	&model.DestinationSystemTypeTranslation{},        //index: 283
	&model.DestinationTranslation{},                  //index: 284
	&model.Device{},                                  //index: 285
	&model.DeviceAsset{},                             //index: 286
	&model.DeviceTranslation{},                       //index: 287
	&model.DimensionCategory{},                       //index: 288
	&model.DimensionCategoryTranslation{},            //index: 289
	&model.DistributionType{},                        //index: 290
	&model.DistributionTypeTranslation{},             //index: 291
	&model.District{},                                //index: 292
	&model.DistrictTranslation{},                     //index: 293
	&model.Division{},                                //index: 294
	&model.DivisionTranslation{},                     //index: 295
	&model.Document{},                                //index: 296
	&model.DocumentAsset{},                           //index: 297
	&model.DocumentType{},                            //index: 298
	&model.DocumentTypeTranslation{},                 //index: 299
	&model.EmailAddressType{},                        //index: 300
	&model.EmailAddressTypeTranslation{},             //index: 301
	&model.EmailCategory{},                           //index: 302
	&model.EmailTemplate{},                           //index: 303
	&model.EmailTemplateRecipientType{},              //index: 304
	&model.EmailTemplateTranslation{},                //index: 305
	&model.Employee{},                                //index: 306
	&model.EmployeeAdditionalRole{},                  //index: 307
	&model.EmployeeAsset{},                           //index: 308
	&model.EnrollmentMethod{},                        //index: 309
	&model.EnrollmentMethodTranslation{},             //index: 310
	&model.Event{},                                   //index: 311
	&model.EventLevel{},                              //index: 312
	&model.EventLevelTranslation{},                   //index: 313
	&model.EventLog{},                                //index: 314
	&model.EventType{},                               //index: 315
	&model.EventTypeTranslation{},                    //index: 316
	&model.EWallet{},                                 //index: 317
	&model.EWalletTranslation{},                      //index: 318
	&model.FareType{},                                //index: 319
	&model.FareTypeTranslation{},                     //index: 320
	&model.FeeTaxType{},                              //index: 321
	&model.FeeTaxTypeTranslation{},                   //index: 322
	&model.FieldType{},                               //index: 323
	&model.FieldTypeTranslation{},                    //index: 324
	&model.FlightCaching{},                           //index: 325
	&model.FlightCachingAddon{},                      //index: 326
	&model.FlightCachingAddonAssignee{},              //index: 327
	&model.FlightCachingAddonAssigneeTemp{},          //index: 328
	&model.FlightCachingAirlines{},                   //index: 329
	&model.FlightCachingAirport{},                    //index: 330
	&model.FlightCachingCabins{},                     //index: 331
	&model.FlightCachingCalculationResult{},          //index: 332
	&model.FlightCachingCalendarFares{},              //index: 333
	&model.FlightCachingCancellationOffer{},          //index: 334
	&model.FlightCachingCommissionClaim{},            //index: 335
	&model.FlightCachingFareDetail{},                 //index: 336
	&model.FlightCachingFareDetailBaggageAllowance{}, //index: 337
	&model.FlightCachingFareDetailTax{},              //index: 338
	&model.FlightCachingFareDetailTaxSummary{},       //index: 339
	&model.FlightCachingFares{},                      //index: 340
	&model.FlightCachingFrequentDestination{},        //index: 341
	&model.FlightCachingIssuing{},                    //index: 342
	&model.FlightCachingMarkup{},                     //index: 343
	&model.FlightCachingMultimedia{},                 //index: 344
	&model.FlightCachingPnrStatus{},                  //index: 345
	&model.FlightCachingProcessingFee{},              //index: 346
	&model.FlightCachingProposal{},                   //index: 347
	&model.FlightCachingRequest{},                    //index: 348
	&model.FlightCachingRequestRoute{},               //index: 349
	&model.FlightCachingRequestStatus{},              //index: 350
	&model.FlightCachingRequestTravellers{},          //index: 351
	&model.FlightCachingReservation{},                //index: 352
	&model.FlightCachingRoutes{},                     //index: 353
	&model.FlightCachingSelectSeat{},                 //index: 354
	// &model.FlightCachingSelectSeatTemp{},                   //index: 355
	&model.FlightCachingSelected{},                         //index: 356
	&model.FlightCachingServiceFee{},                       //index: 357
	&model.FlightCachingSession{},                          //index: 358
	&model.FlightCachingSources{},                          //index: 359
	&model.FlightCachingTax{},                              //index: 360
	&model.FlightCachingTicket{},                           //index: 361
	&model.FlightCachingTravelPolicyViolation{},            //index: 362
	&model.FlightCachingTraveller{},                        //index: 363
	&model.FlightSegment{},                                 //index: 364
	&model.FlightSegmentStopLocation{},                     //index: 365
	&model.FlightType{},                                    //index: 366
	&model.FlightTypeTranslation{},                         //index: 367
	&model.FlightViolationReason{},                         //index: 368
	&model.Form{},                                          //index: 369
	&model.FormField{},                                     //index: 370
	&model.FormFieldOption{},                               //index: 371
	&model.FormFieldOptionTranslation{},                    //index: 372
	&model.FormFieldTranslation{},                          //index: 373
	&model.FormTranslation{},                               //index: 374
	&model.FormType{},                                      //index: 375
	&model.FormTypeTranslation{},                           //index: 376
	&model.Gender{},                                        //index: 377
	&model.GenderTranslation{},                             //index: 378
	&model.GuaranteeType{},                                 //index: 379
	&model.GuaranteeTypeTranslation{},                      //index: 380
	&model.GuestRoomInfoType{},                             //index: 381
	&model.GuestRoomInfoTypeTranslation{},                  //index: 382
	&model.Hotel{},                                         //index: 383
	&model.HotelAmenityCategory{},                          //index: 384
	&model.HotelAmenityCategoryAsset{},                     //index: 385
	&model.HotelAmenityCategoryHotelAmenityType{},          //index: 386
	&model.HotelAmenityCategoryTranslation{},               //index: 387
	&model.HotelAmenityType{},                              //index: 388
	&model.HotelAmenityTypeAsset{},                         //index: 389
	&model.HotelAmenityTypeTranslation{},                   //index: 390
	&model.HotelAsset{},                                    //index: 391
	&model.HotelAttraction{},                               //index: 392
	&model.HotelBrand{},                                    //index: 393
	&model.HotelBrandTranslation{},                         //index: 394
	&model.HotelFacility{},                                 //index: 395
	&model.HotelFacilityAsset{},                            //index: 396
	&model.HotelFacilityTranslation{},                      //index: 397
	&model.HotelPolicy{},                                   //index: 398
	&model.HotelPolicyTranslation{},                        //index: 399
	&model.HotelRating{},                                   //index: 400
	&model.HotelReferencePoint{},                           //index: 401
	&model.HotelSupplier{},                                 //index: 402
	&model.HotelSupplierTranslation{},                      //index: 403
	&model.HotelTranslation{},                              //index: 404
	&model.Industry{},                                      //index: 405
	&model.IndustryTranslation{},                           //index: 406
	&model.InformationType{},                               //index: 407
	&model.InformationTypeTranslation{},                    //index: 408
	&model.Inquiry{},                                       //index: 409
	&model.InquiryProfile{},                                //index: 410
	&model.IntegrationPartner{},                            //index: 411
	&model.IntegrationPartnerAirline{},                     //index: 412
	&model.IntegrationPartnerCabinType{},                   //index: 413
	&model.IntegrationPartnerCity{},                        //index: 414
	&model.IntegrationPartnerCityTranslation{},             //index: 415
	&model.IntegrationPartnerCorporate{},                   //index: 416
	&model.IntegrationPartnerCorporateGroup{},              //index: 417
	&model.IntegrationPartnerCountry{},                     //index: 418
	&model.IntegrationPartnerCountryTranslation{},          //index: 419
	&model.IntegrationPartnerCreditCardType{},              //index: 420
	&model.IntegrationPartnerCurrency{},                    //index: 421
	&model.IntegrationPartnerCurrencyTranslation{},         //index: 422
	&model.IntegrationPartnerDestination{},                 //index: 423
	&model.IntegrationPartnerDestinationTranslation{},      //index: 424
	&model.IntegrationPartnerEvent{},                       //index: 425
	&model.IntegrationPartnerFareFamily{},                  //index: 426
	&model.IntegrationPartnerFeeTaxType{},                  //index: 427
	&model.IntegrationPartnerHotel{},                       //index: 428
	&model.IntegrationPartnerHotelAmenityType{},            //index: 429
	&model.IntegrationPartnerHotelAmenityTypeTranslation{}, //index: 430
	&model.IntegrationPartnerHotelGroup{},                  //index: 431
	&model.IntegrationPartnerHotelGroupTranslation{},       //index: 432
	&model.IntegrationPartnerHotelRatePlan{},               //index: 433
	&model.IntegrationPartnerHotelRatePlanTranslation{},    //index: 434
	&model.IntegrationPartnerHotelRatingType{},             //index: 435
	&model.IntegrationPartnerHotelRatingTypeTranslation{},  //index: 436
	&model.IntegrationPartnerHotelRoomType{},               //index: 437
	&model.IntegrationPartnerHotelRoomTypeOccupancy{},      //index: 438
	&model.IntegrationPartnerHotelRoomTypeTranslation{},    //index: 439
	&model.IntegrationPartnerHotelSupplier{},               //index: 440
	&model.IntegrationPartnerHotelTranslation{},            //index: 441
	&model.IntegrationPartnerLanguage{},                    //index: 442
	&model.IntegrationPartnerLocationCategory{},            //index: 443
	&model.IntegrationPartnerLocationCategoryTranslation{}, //index: 444
	&model.IntegrationPartnerMealPlanType{},                //index: 445
	&model.IntegrationPartnerMealPlanTypeTranslation{},     //index: 446
	&model.IntegrationPartnerNamePrefix{},                  //index: 447
	&model.IntegrationPartnerPassengerType{},               //index: 448
	&model.IntegrationPartnerPaymentGateway{},              //index: 449
	&model.IntegrationPartnerPromotion{},                   //index: 450
	&model.IntegrationPartnerPromotionTranslation{},        //index: 451
	&model.IntegrationPartnerPropertyCategory{},            //index: 452
	&model.IntegrationPartnerPropertyCategoryTranslation{}, //index: 453
	&model.IntegrationPartnerRoomAmenityType{},             //index: 454
	&model.IntegrationPartnerRoomAmenityTypeTranslation{},  //index: 455
	&model.IntegrationPartnerSegmentCategory{},             //index: 456
	&model.IntegrationPartnerSegmentCategoryTranslation{},  //index: 457
	&model.IntegrationPartnerSetting{},                     //index: 458
	&model.IntegrationPartnerSpecialRequest{},              //index: 459
	&model.IntegrationPartnerStateProvince{},               //index: 460
	&model.IntegrationPartnerStateProvinceTranslation{},    //index: 461
	&model.IntegrationPartnerStatus{},                      //index: 462
	&model.IntegrationPartnerTransaction{},                 //index: 463
	&model.IntegrationPartnerType{},                        //index: 464
	&model.IntegrationPartnerZone{},                        //index: 465
	&model.IntegrationPartnerZoneTranslation{},             //index: 466
	&model.JobTitle{},                                      //index: 467
	&model.JobTitleTranslation{},                           //index: 468
	&model.Language{},                                      //index: 469
	&model.LanguageAsset{},                                 //index: 470
	&model.LanguageTranslation{},                           //index: 471
	&model.LocationCategory{},                              //index: 472
	&model.LocationCategoryTranslation{},                   //index: 473
	&model.LoyaltyAccount{},                                //index: 474
	&model.LoyaltyAccountAsset{},                           //index: 475
	&model.LoyaltyAccountBalance{},                         //index: 476
	&model.LoyaltyAccountContent{},                         //index: 477
	&model.LoyaltyAccountVoucher{},                         //index: 478
	&model.LoyaltyBonus{},                                  //index: 479
	&model.LoyaltyCancelPenalty{},                          //index: 480
	&model.LoyaltyConversionRate{},                         //index: 481
	&model.LoyaltyLevel{},                                  //index: 482
	&model.LoyaltyLevelAsset{},                             //index: 483
	&model.LoyaltyLevelContent{},                           //index: 484
	&model.LoyaltyLevelTranslation{},                       //index: 485
	&model.LoyaltyProgram{},                                //index: 486
	&model.LoyaltyProgramAirline{},                         //index: 487
	&model.LoyaltyProgramAsset{},                           //index: 488
	&model.LoyaltyProgramBenefit{},                         //index: 489
	&model.LoyaltyProgramContent{},                         //index: 490
	&model.LoyaltyProgramHotelBrand{},                      //index: 491
	&model.LoyaltyProgramProductType{},                     //index: 492
	&model.LoyaltyProgramRewardCategory{},                  //index: 493
	&model.LoyaltyProgramRewardType{},                      //index: 494
	&model.LoyaltyProgramSetting{},                         //index: 495
	&model.LoyaltyProgramTranslation{},                     //index: 496
	&model.LoyaltyPurchaseDiscount{},                       //index: 497
	&model.LoyaltyPurchaseRate{},                           //index: 498
	&model.MaritalStatus{},                                 //index: 499
	&model.MaritalStatusTranslation{},                      //index: 500
	&model.Market{},                                        //index: 501
	&model.MarketTranslation{},                             //index: 502
	&model.MarkupCategory{},                                //index: 503
	&model.MarkupCategoryTranslation{},                     //index: 504
	&model.MarkupRate{},                                    //index: 505
	&model.MarkupRateAirline{},                             //index: 506
	&model.MarkupRateAirlineCategory{},                     //index: 507
	&model.MarkupRateCity{},                                //index: 508
	&model.MarkupRateCountry{},                             //index: 509
	&model.MarkupRateDestinationGroup{},                    //index: 510
	&model.MarkupRateHotel{},                               //index: 511
	&model.MarkupRateHotelSupplier{},                       //index: 512
	&model.MarkupRateProductCategory{},                     //index: 513
	&model.MarkupRateProductType{},                         //index: 514
	&model.MarkupRateSupplierType{},                        //index: 515
	&model.MarkupRateTranslation{},                         //index: 516
	&model.MealPlanType{},                                  //index: 517
	&model.MealPlanTypeAsset{},                             //index: 518
	&model.MealPlanTypeTranslation{},                       //index: 519
	&model.Menu{},                                          //index: 520
	&model.MenuLink{},                                      //index: 521
	&model.MenuLinkAsset{},                                 //index: 522
	&model.MenuLinkTranslation{},                           //index: 523
	&model.MenuLinkType{},                                  //index: 524
	&model.MenuLinkTypeTranslation{},                       //index: 525
	&model.MenuTranslation{},                               //index: 526
	&model.Message{},                                       //index: 527
	&model.MessageAsset{},                                  //index: 528
	&model.MessageCategory{},                               //index: 529
	&model.MessageHistory{},                                //index: 530
	&model.MessagePriority{},                               //index: 531
	&model.MessageRecipient{},                              //index: 532
	&model.MessageType{},                                   //index: 533
	&model.MessageTypeTranslation{},                        //index: 534
	&model.MessageVariable{},                               //index: 535
	&model.MessageVariableTranslation{},                    //index: 536
	&model.Metrics{},                                       //index: 537
	&model.MetricsTranslation{},                            //index: 538
	&model.ModifyPolicy{},                                  //index: 539
	&model.ModifyPolicyTranslation{},                       //index: 540
	&model.Module{},                                        //index: 541
	&model.ModuleCapability{},                              //index: 542
	&model.ModulePackage{},                                 //index: 543
	&model.ModulePackageTranslation{},                      //index: 544
	&model.ModulePage{},                                    //index: 545
	&model.ModuleTranslation{},                             //index: 546
	&model.MultimediaDescription{},                         //index: 547
	&model.MultimediaDescriptionTranslation{},              //index: 548
	&model.NamePrefix{},                                    //index: 549
	&model.NamePrefixTranslation{},                         //index: 550
	&model.OccupancyType{},                                 //index: 551
	&model.OccupancyTypeTranslation{},                      //index: 552
	&model.OfferType{},                                     //index: 553
	&model.OfferTypeRatePlanType{},                         //index: 554
	&model.OfferTypeTranslation{},                          //index: 555
	&model.Office{},                                        //index: 556
	&model.OfficeOperationSchedule{},                       //index: 557
	&model.OfficeTranslation{},                             //index: 558
	&model.OffsetDropTime{},                                //index: 559
	&model.OffsetDropTimeTranslation{},                     //index: 560
	&model.OffsetTimeUnit{},                                //index: 561
	&model.OffsetTimeUnitTranslation{},                     //index: 562
	&model.OperatingSystem{},                               //index: 563
	&model.OperatingSystemAsset{},                          //index: 564
	&model.OperatingSystemTranslation{},                    //index: 565
	&model.OperationSchedule{},                             //index: 566
	&model.OperationScheduleTranslation{},                  //index: 567
	&model.OperationTime{},                                 //index: 568
	&model.OpsigoFareDetailPrice{},                         //index: 569
	&model.OpsigoFareDetailTax{},                           //index: 570
	&model.OpsigoFlightClassCaching{},                      //index: 571
	&model.OpsigoFlightFareCaching{},                       //index: 572
	&model.OpsigoFlightSeatCaching{},                       //index: 573
	&model.Page{},                                          //index: 574
	&model.PageAsset{},                                     //index: 575
	&model.PageDestination{},                               //index: 576
	&model.PageLink{},                                      //index: 577
	&model.PagePlacementUnit{},                             //index: 578
	&model.PageRelated{},                                   //index: 579
	&model.PageSetting{},                                   //index: 580
	&model.PageTerm{},                                      //index: 581
	&model.PageTranslation{},                               //index: 582
	&model.PageType{},                                      //index: 583
	&model.PageTypeTranslation{},                           //index: 584
	&model.PageWidget{},                                    //index: 585
	&model.PassengerType{},                                 //index: 586
	&model.PassengerTypeTranslation{},                      //index: 587
	&model.PasswordHistory{},                               //index: 588
	&model.PaymentGateway{},                                //index: 589
	&model.PaymentGatewayAsset{},                           //index: 590
	&model.PaymentGatewayTranslation{},                     //index: 591
	&model.PaymentTransaction{},                            //index: 592
	&model.PaymentType{},                                   //index: 593
	&model.PaymentTypeTranslation{},                        //index: 594
	&model.Person{},                                        //index: 595
	&model.PersonFormField{},                               //index: 596
	&model.PersonFormFieldSelection{},                      //index: 597
	&model.PersonPreference{},                              //index: 598
	&model.PersonPreferenceSelection{},                     //index: 599
	&model.PhoneLocationType{},                             //index: 600
	&model.PhoneLocationTypeTranslation{},                  //index: 601
	&model.PhoneTechnologyType{},                           //index: 602
	&model.PhoneTechnologyTypeTranslation{},                //index: 603
	&model.PhoneUseType{},                                  //index: 604
	&model.PhoneUseTypeTranslation{},                       //index: 605
	&model.PictureCategory{},                               //index: 606
	&model.PictureCategoryTranslation{},                    //index: 607
	&model.Preference{},                                    //index: 608
	&model.PreferenceOption{},                              //index: 609
	&model.PreferenceOptionTranslation{},                   //index: 610
	&model.PreferenceTranslation{},                         //index: 611
	&model.PreferenceType{},                                //index: 612
	&model.PreferenceTypeTranslation{},                     //index: 613
	&model.ProcessingFeeCategory{},                         //index: 614
	&model.ProcessingFeeCategoryTranslation{},              //index: 615
	&model.ProcessingFeeRate{},                             //index: 616
	&model.ProcessingFeeRateAirline{},                      //index: 617
	&model.ProcessingFeeRateAirlineCategory{},              //index: 618
	&model.ProcessingFeeRateDestinationGroup{},             //index: 619
	&model.ProcessingFeeRateHotelSupplier{},                //index: 620
	&model.ProcessingFeeRateProductCategory{},              //index: 621
	&model.ProcessingFeeRateProductType{},                  //index: 622
	&model.ProcessingFeeRateSupplierType{},                 //index: 623
	&model.ProcessingFeeRateTranslation{},                  //index: 624
	&model.Product{},                                       //index: 625
	&model.ProductAsset{},                                  //index: 626
	&model.ProductCategory{},                               //index: 627
	&model.ProductCategoryProduct{},                        //index: 628
	&model.ProductCategoryTranslation{},                    //index: 629
	&model.ProductPurchase{},                               //index: 630
	&model.ProductPurchaseCancelPolicy{},                   //index: 631
	&model.ProductPurchaseCancelPolicyPenalty{},            //index: 632
	&model.ProductPurchaseGuaranteePaymentPolicy{},         //index: 633
	&model.ProductPurchaseModifyPolicy{},                   //index: 634
	&model.ProductPurchasePayment{},                        //index: 635
	&model.ProductPurchaseReward{},                         //index: 636
	&model.ProductPurchaseVoucher{},                        //index: 637
	&model.ProductTranslation{},                            //index: 638
	&model.ProductType{},                                   //index: 639
	&model.ProductTypeTranslation{},                        //index: 640
	&model.ProfileStatus{},                                 //index: 641
	&model.ProfileStatusTranslation{},                      //index: 642
	&model.ProfileType{},                                   //index: 643
	&model.ProfileTypeTranslation{},                        //index: 644
	&model.Project{},                                       //index: 645
	&model.ProjectTranslation{},                            //index: 646
	&model.PropertyCategory{},                              //index: 647
	&model.PropertyCategoryTranslation{},                   //index: 648
	&model.Proposal{},                                      //index: 649
	&model.ProposalAdditionalInfo{},                        //index: 650
	&model.ProposalAdditionalInfoSelection{},               //index: 651
	&model.ProposalAirItinerary{},                          //index: 652
	&model.ProposalAsset{},                                 //index: 653
	&model.ProposalBudget{},                                //index: 654
	&model.ProposalBusinessPartner{},                       //index: 655
	&model.ProposalCommissionClaim{},                       //index: 656
	&model.ProposalHistory{},                               //index: 657
	&model.ProposalMarkupCategory{},                        //index: 658
	&model.ProposalMarkupRate{},                            //index: 659
	&model.ProposalOffer{},                                 //index: 660
	&model.ProposalOfferDiscount{},                         //index: 661
	&model.ProposalPayload{},                               //index: 662
	&model.ProposalProcessingFeeCategory{},                 //index: 663
	&model.ProposalProcessingFeeRate{},                     //index: 664
	&model.ProposalProduct{},                               //index: 665
	&model.ProposalProductPrice{},                          //index: 666
	&model.ProposalProductPriceType{},                      //index: 667
	&model.ProposalProductPurchase{},                       //index: 668
	&model.ProposalProfile{},                               //index: 669
	&model.ProposalRatePlan{},                              //index: 670
	&model.ProposalRoomStay{},                              //index: 671
	&model.ProposalRoomType{},                              //index: 672
	&model.ProposalServiceFeeCategory{},                    //index: 673
	&model.ProposalServiceFeeRate{},                        //index: 674
	&model.ProposalSpecialRequest{},                        //index: 675
	&model.ProposalTaxCategory{},                           //index: 676
	&model.ProposalTaxRate{},                               //index: 677
	&model.Proximity{},                                     //index: 678
	&model.ProximityTranslation{},                          //index: 679
	&model.Queue{},                                         //index: 680
	&model.QueueType{},                                     //index: 681
	&model.QueueTypeTranslation{},                          //index: 682
	&model.RatePlanType{},                                  //index: 683
	&model.RatePlanTypeTranslation{},                       //index: 684
	&model.RateTimeUnit{},                                  //index: 685
	&model.RateTimeUnitTranslation{},                       //index: 686
	&model.RatingType{},                                    //index: 687
	&model.RatingTypeLevel{},                               //index: 688
	&model.RatingTypeLevelTranslation{},                    //index: 689
	&model.RatingTypeTranslation{},                         //index: 690
	&model.RecipientType{},                                 //index: 691
	&model.RecipientTypeTranslation{},                      //index: 692
	&model.RecurrenceType{},                                //index: 693
	&model.RecurrenceTypeTranslation{},                     //index: 694
	&model.RedemptionNominee{},                             //index: 695
	&model.ReferencePoint{},                                //index: 696
	&model.ReferencePointCategory{},                        //index: 697
	&model.ReferencePointCategoryTranslation{},             //index: 698
	&model.ReferencePointTranslation{},                     //index: 699
	&model.ReferralSource{},                                //index: 700
	&model.ReferralSourceTranslation{},                     //index: 701
	&model.Region{},                                        //index: 702
	&model.RegionTranslation{},                             //index: 703
	&model.RelationSchema{},                                //index: 704
	&model.Religion{},                                      //index: 705
	&model.ReligionTranslation{},                           //index: 706
	&model.Reservation{},                                   //index: 707
	&model.ReservationAdditionalInfo{},                     //index: 708
	&model.ReservationAdditionalInfoSelection{},            //index: 709
	&model.ReservationAirItinerary{},                       //index: 710
	&model.ReservationAsset{},                              //index: 711
	&model.ReservationBudget{},                             //index: 712
	&model.ReservationBusinessPartner{},                    //index: 713
	&model.ReservationCommission{},                         //index: 714
	&model.ReservationCommissionClaim{},                    //index: 715
	&model.ReservationContact{},                            //index: 716
	&model.ReservationHistory{},                            //index: 717
	&model.ReservationIdentifier{},                         //index: 718
	&model.ReservationMarkupCategory{},                     //index: 719
	&model.ReservationMarkupRate{},                         //index: 720
	&model.ReservationOffer{},                              //index: 721
	&model.ReservationOfferDiscount{},                      //index: 722
	&model.ReservationPayload{},                            //index: 723
	&model.ReservationProcessingFeeCategory{},              //index: 724
	&model.ReservationProcessingFeeRate{},                  //index: 725
	&model.ReservationProduct{},                            //index: 726
	&model.ReservationProductPrice{},                       //index: 727
	&model.ReservationProductPriceType{},                   //index: 728
	&model.ReservationProductPurchase{},                    //index: 729
	&model.ReservationProductVoucherType{},                 //index: 730
	&model.ReservationProfile{},                            //index: 731
	&model.ReservationRatePlan{},                           //index: 732
	&model.ReservationRoomStay{},                           //index: 733
	&model.ReservationRoomType{},                           //index: 734
	&model.ReservationServiceFeeCategory{},                 //index: 735
	&model.ReservationServiceFeeRate{},                     //index: 736
	&model.ReservationTaxCategory{},                        //index: 737
	&model.ReservationTaxRate{},                            //index: 738
	&model.RewardCategory{},                                //index: 739
	&model.RewardRate{},                                    //index: 740
	&model.RewardRateAirline{},                             //index: 741
	&model.RewardRateAirlineCategory{},                     //index: 742
	&model.RewardRateDestinationGroup{},                    //index: 743
	&model.RewardRateHotelSupplier{},                       //index: 744
	&model.RewardRateProductCategory{},                     //index: 745
	&model.RewardRateProductType{},                         //index: 746
	&model.RewardRateSupplierType{},                        //index: 747
	&model.RewardRateTranslation{},                         //index: 748
	&model.RewardType{},                                    //index: 749
	&model.RewardTypeTranslation{},                         //index: 750
	&model.RoomAmenityCategory{},                           //index: 751
	&model.RoomAmenityCategoryAsset{},                      //index: 752
	&model.RoomAmenityCategoryRoomAmenityType{},            //index: 753
	&model.RoomAmenityCategoryTranslation{},                //index: 754
	&model.RoomAmenityType{},                               //index: 755
	&model.RoomAmenityTypeAsset{},                          //index: 756
	&model.RoomAmenityTypeTranslation{},                    //index: 757
	&model.RoomClassification{},                            //index: 758
	&model.RoomClassificationTranslation{},                 //index: 759
	&model.RoomLocationType{},                              //index: 760
	&model.RoomLocationTypeTranslation{},                   //index: 761
	&model.RoomRate{},                                      //index: 762
	&model.RoomStay{},                                      //index: 763
	&model.RoomStayGuest{},                                 //index: 764
	&model.RoomStayPayment{},                               //index: 765
	&model.RoomType{},                                      //index: 766
	&model.RoomTypeTranslation{},                           //index: 767
	&model.RoomViewType{},                                  //index: 768
	&model.RoomViewTypeTranslation{},                       //index: 769
	&model.RoundNumberDigit{},                              //index: 770
	&model.RoundNumberDigitTranslation{},                   //index: 771
	&model.RoundNumberFunction{},                           //index: 772
	&model.RoundNumberFunctionTranslation{},                //index: 773
	&model.SabreAirPassengerTotalFareMessage{},             //index: 774
	&model.SabreCache{},                                    //index: 775
	&model.SabreCacheAddons{},                              //index: 776
	&model.SabreCacheAirRules{},                            //index: 777
	&model.SabreCacheAirRulesHeader{},                      //index: 778
	&model.SabreCacheAirRulesRules{},                       //index: 779
	&model.SabreCacheAirRulesStatus{},                      //index: 780
	&model.SabreFlightSession{},                            //index: 781
	&model.SabreCacheSelected{},                            //index: 782
	&model.SabreCacheTravellers{},                          //index: 783
	&model.SabreIntegration{},                              //index: 784
	&model.SabreLogError{},                                 //index: 785
	&model.SabreTraceLog{},                                 //index: 786
	&model.Schedule{},                                      //index: 787
	&model.SecurityFeature{},                               //index: 788
	&model.SecurityFeatureTranslation{},                    //index: 789
	&model.SegmentCategory{},                               //index: 790
	&model.SegmentCategoryTranslation{},                    //index: 791
	&model.ServiceFeeCategory{},                            //index: 792
	&model.ServiceFeeCategoryTranslation{},                 //index: 793
	&model.ServiceFeeDestination{},                         //index: 794
	&model.ServiceFeeRate{},                                //index: 795
	&model.ServiceFeeRateAirline{},                         //index: 796
	&model.ServiceFeeRateAirlineCategory{},                 //index: 797
	&model.ServiceFeeRateDestinationGroup{},                //index: 798
	&model.ServiceFeeRateHotelSupplier{},                   //index: 799
	&model.ServiceFeeRateProductCategory{},                 //index: 800
	&model.ServiceFeeRateProductType{},                     //index: 801
	&model.ServiceFeeRateSupplierType{},                    //index: 802
	&model.ServiceFeeRateTranslation{},                     //index: 803
	&model.ServiceLevel{},                                  //index: 804
	&model.ServiceLevelObjective{},                         //index: 805
	&model.ServiceLevelTranslation{},                       //index: 806
	&model.Session{},                                       //index: 807
	&model.Site{},                                          //index: 808
	&model.SiteAsset{},                                     //index: 809
	&model.SiteContent{},                                   //index: 810
	&model.SiteCurrency{},                                  //index: 811
	&model.SiteLanguage{},                                  //index: 812
	&model.SiteSetting{},                                   //index: 813
	&model.SiteTheme{},                                     //index: 814
	&model.SiteTranslation{},                               //index: 815
	&model.SiteType{},                                      //index: 816
	&model.SiteTypeTranslation{},                           //index: 817
	&model.SocialNetwork{},                                 //index: 818
	&model.SocialNetworkAsset{},                            //index: 819
	&model.SocialNetworkTranslation{},                      //index: 820
	&model.SpecialRequest{},                                //index: 821
	&model.SpecialRequestTranslation{},                     //index: 822
	&model.SqNdcCacheOfferService{},                        //index: 823
	&model.SqNdcCacheOffersFareComponent{},                 //index: 824
	&model.SqNdcCacheOrder{},                               //index: 825
	&model.SqNdcCacheOriginDest{},                          //index: 826
	&model.SqNdcCachePax{},                                 //index: 827
	&model.SqNdcCacheReshopOffer{},                         //index: 828
	&model.SqNdcCacheSelectedOffer{},                       //index: 829
	&model.SqNdcCacheService{},                             //index: 830
	&model.SqNdcCacheShoppingResponse{},                    //index: 831
	&model.SqNdcCacheTicket{},                              //index: 832
	&model.StateProvince{},                                 //index: 833
	&model.StateProvinceCategory{},                         //index: 834
	&model.StateProvinceCategoryTranslation{},              //index: 835
	&model.StateProvinceTranslation{},                      //index: 836
	&model.Status{},                                        //index: 837
	&model.StatusCategory{},                                //index: 838
	&model.StatusTranslation{},                             //index: 839
	&model.Subdistrict{},                                   //index: 840
	&model.SubdistrictTranslation{},                        //index: 841
	&model.SupplierType{},                                  //index: 842
	&model.SupplierTypeTranslation{},                       //index: 843
	&model.TaskType{},                                      //index: 844
	&model.TaskTypeTranslation{},                           //index: 845
	&model.TaxCategory{},                                   //index: 846
	&model.TaxRate{},                                       //index: 847
	&model.TaxRateDestinationGroup{},                       //index: 848
	&model.TaxRateProductType{},                            //index: 849
	&model.Team{},                                          //index: 850
	&model.TeamTranslation{},                               //index: 851
	&model.Term{},                                          //index: 852
	&model.TermCategory{},                                  //index: 853
	&model.TermCategoryTerm{},                              //index: 854
	&model.TermCategoryTranslation{},                       //index: 855
	&model.TermTranslation{},                               //index: 856
	&model.Theme{},                                         //index: 857
	&model.ThemeAsset{},                                    //index: 858
	&model.ThemeLocation{},                                 //index: 859
	&model.ThemeLocationContent{},                          //index: 860
	&model.ThemeLocationMenu{},                             //index: 861
	&model.ThemeLocationTranslation{},                      //index: 862
	&model.ThemeLocationWidget{},                           //index: 863
	&model.ThemeTranslation{},                              //index: 864
	&model.ThemeType{},                                     //index: 865
	&model.ThemeTypeTranslation{},                          //index: 866
	&model.TimeZone{},                                      //index: 867
	&model.TimeZoneTranslation{},                           //index: 868
	&model.Tooltip{},                                       //index: 869
	&model.TooltipAsset{},                                  //index: 870
	&model.TooltipTranslation{},                            //index: 871
	&model.TransportInfo{},                                 //index: 872
	&model.TransportationMode{},                            //index: 873
	&model.TransportationModeTranslation{},                 //index: 874
	&model.TravelPolicy{},                                  //index: 875
	&model.TravelPolicyAirline{},                           //index: 876
	&model.TravelPolicyAirlineCategory{},                   //index: 877
	&model.TravelPolicyCabinType{},                         //index: 878
	&model.TravelPolicyClass{},                             //index: 879
	&model.TravelPolicyClassJobTitle{},                     //index: 880
	&model.TravelPolicyClassTranslation{},                  //index: 881
	&model.TravelPolicyDestinationGroup{},                  //index: 882
	&model.TravelPolicyJobTitle{},                          //index: 883
	&model.TravelPolicyPlafondAmount{},                     //index: 884
	&model.TravelPolicyProductType{},                       //index: 885
	&model.TravelPolicyPropertyCategory{},                  //index: 886
	&model.TravelPolicyRatingType{},                        //index: 887
	&model.TravelPolicyTranslation{},                       //index: 888
	&model.TravelPurpose{},                                 //index: 889
	&model.TravelPurposeTranslation{},                      //index: 890
	&model.TripType{},                                      //index: 891
	&model.TripTypeTranslation{},                           //index: 892
	&model.UniqueIDType{},                                  //index: 893
	&model.UniqueIDTypeTranslation{},                       //index: 894
	&model.UnitOfMeasure{},                                 //index: 895
	&model.UnitOfMeasureTranslation{},                      //index: 896
	&model.URLType{},                                       //index: 897
	&model.URLTypeTranslation{},                            //index: 898
	&model.UserAccount{},                                   //index: 899
	&model.UserAsset{},                                     //index: 900
	&model.UserMenuLink{},                                  //index: 901
	&model.UserModuleCapability{},                          //index: 902
	&model.UserSetting{},                                   //index: 903
	&model.UserSocialNetwork{},                             //index: 904
	&model.UserThrottle{},                                  //index: 905
	&model.UserType{},                                      //index: 906
	&model.UserTypeMenuLink{},                              //index: 907
	&model.UserTypeModuleCapability{},                      //index: 908
	&model.UserTypeTranslation{},                           //index: 909
	&model.UserTypeUser{},                                  //index: 910
	&model.Viewership{},                                    //index: 911
	&model.ViewershipAccessCode{},                          //index: 912
	&model.ViewershipBusinessPartner{},                     //index: 913
	&model.ViewershipBusinessPartnerGroup{},                //index: 914
	&model.ViewershipBusinessPartnerType{},                 //index: 915
	&model.ViewershipDestinationSystem{},                   //index: 916
	&model.ViewershipDevice{},                              //index: 917
	&model.ViewershipLocation{},                            //index: 918
	&model.ViewershipLoyaltyLevel{},                        //index: 919
	&model.ViewershipTranslation{},                         //index: 920
	&model.ViolationReason{},                               //index: 921
	&model.ViolationReasonTranslation{},                    //index: 922
	&model.Voucher{},                                       //index: 923
	&model.VoucherAsset{},                                  //index: 924
	&model.VoucherTranslation{},                            //index: 925
	&model.VoucherType{},                                   //index: 926
	&model.VoucherTypeAsset{},                              //index: 927
	&model.VoucherTypeTranslation{},                        //index: 928
	&model.Widget{},                                        //index: 929
	&model.WidgetSetting{},                                 //index: 930
	&model.WidgetTranslation{},                             //index: 931
	&model.WidgetType{},                                    //index: 932
	&model.WidgetTypeTranslation{},                         //index: 933
	&model.Zone{},                                          //index: 934
	&model.ZoneTranslation{},                               //index: 935

}
